name: Go-test
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.x'
          cache: true

      - name: Create golangci-lint config
        run: |
          echo "run:" > .golangci.yml
          echo "  go: '1.22'" >> .golangci.yml

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test ./...

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - name: Run golangci-lint
        run: $(go env GOPATH)/bin/golangci-lint run --timeout=5m ./...

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
      - name: Run staticcheck
        run: staticcheck ./...

      - name: Install gofumpt
        run: go install mvdan.cc/gofumpt@latest
      - name: Run gofumpt
        run: gofumpt -l -extra .
